# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/hrims
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SWAGGER
# ===============================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# ===============================
# SERVER
# ===============================

server.port=8080